# Inventory Management Deployment with LoadBalancer Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: s224169428registry.azurecr.io/inventory_management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: DATABASE_URL
              value: "postgresql://s224169428_u82i_user:Et5fh8z5bv8pYjnUS2heiU1d0UYjxP13@dpg-crcormaj1k6c73cqg47g-a.oregon-postgres.render.com/s224169428_u82i?sslmode=require"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
    - port: 80
      targetPort: 7000
